const User = require('../models/user.model');
const Submission = require('../models/submission.model');
const Task = require('../models/task.model');
const Project = require('../models/project.model');

/**
 * Get user's portfolio data
 */
async function getUserPortfolio(userId) {
  const user = await User.findById(userId).select('username email avatar skills completedTasks');
  
  if (!user) {
    const err = new Error('User not found');
    err.status = 404;
    throw err;
  }

  // Get accepted submissions only
  const submissions = await Submission.find({
    user: userId,
    status: 'accepted',
    portfolioVisible: true
  })
    .populate('task', 'title description')
    .populate('project', 'title description')
    .select('-__v');

  // Format portfolio data
  const portfolio = {
    profile: {
      username: user.username,
      email: user.email,
      avatar: user.avatar,
      stats: {
        completedTasks: user.completedTasks
      },
      skills: user.skills
    },
    projects: submissions.map(sub => ({
      _id: sub._id,
      taskTitle: sub.task.title,
      taskDescription: sub.task.description,
      projectTitle: sub.project.title,
      projectDescription: sub.project.description,
      score: sub.score,
      feedback: sub.aiFeedback || sub.humanFeedback,
      submissionDate: sub.createdAt,
      repoLink: sub.repoLink,
      submissionLink: sub.submissionLink
    }))
  };

  return portfolio;
}

/**
 * Export portfolio as JSON
 */
async function exportPortfolioJSON(userId) {
  const portfolio = await getUserPortfolio(userId);
  
  return {
    exportedAt: new Date(),
    data: portfolio
  };
}

/**
 * Export portfolio as markdown for GitHub
 */
async function exportPortfolioMarkdown(userId) {
  const portfolio = await getUserPortfolio(userId);
  const { profile, projects } = portfolio;

  let markdown = `# ${profile.username}'s Development Portfolio\n\n`;
  markdown += `**Email:** ${profile.email}\n\n`;
  
  markdown += `## 📊 Stats\n`;
  markdown += `- **Tasks Completed:** ${profile.stats.completedTasks}\n\n`;

  markdown += `## 🛠 Skills\n`;
  Object.entries(profile.skills).forEach(([skill, data]) => {
    if (data.level) {
      markdown += `- **${skill}:** ${data.level} (${data.score}%)\n`;
    }
  });
  markdown += `\n`;

  markdown += `## 🎯 Projects\n\n`;
  projects.forEach((project, idx) => {
    markdown += `### ${idx + 1}. ${project.taskTitle}\n`;
    markdown += `**Project:** ${project.projectTitle}\n`;
    markdown += `**Description:** ${project.taskDescription}\n`;
    markdown += `**Score:** ${project.score}/100\n`;
    if (project.repoLink) {
      markdown += `**Repository:** [View on GitHub](${project.repoLink})\n`;
    }
    if (project.submissionLink) {
      markdown += `**Live Demo:** [View Live](${project.submissionLink})\n`;
    }
    markdown += `**Feedback:** ${project.feedback || 'N/A'}\n`;
    markdown += `**Date:** ${new Date(project.submissionDate).toLocaleDateString()}\n\n`;
  });

  markdown += `---\n`;
  markdown += `*Generated by Team Management Platform*\n`;

  return markdown;
}

/**
 * Export portfolio as CSV for tracking
 */
async function exportPortfolioCSV(userId) {
  const portfolio = await getUserPortfolio(userId);
  const { projects } = portfolio;

  let csv = 'Task,Project,Score,Submission Date,Repo Link,Demo Link\n';
  
  projects.forEach(project => {
    csv += `"${project.taskTitle}","${project.projectTitle}",${project.score},"${new Date(project.submissionDate).toLocaleDateString()}","${project.repoLink || ''}","${project.submissionLink || ''}"\n`;
  });

  return csv;
}

/**
 * Get portfolio statistics
 */
async function getPortfolioStats(userId) {
  const acceptedSubmissions = await Submission.find({
    user: userId,
    status: 'accepted'
  }).populate('task', 'difficulty');
  const averageScore = acceptedSubmissions.length > 0
    ? Math.round(acceptedSubmissions.reduce((sum, sub) => sum + (sub.score || 0), 0) / acceptedSubmissions.length)
    : 0;

  const projectsByDifficulty = {};
  acceptedSubmissions.forEach(sub => {
    const difficulty = sub.task?.difficulty || 'unknown';
    projectsByDifficulty[difficulty] = (projectsByDifficulty[difficulty] || 0) + 1;
  });

  return {
    totalProjects: acceptedSubmissions.length,
    averageScore,
    projectsByDifficulty
  };
}

module.exports = {
  getUserPortfolio,
  exportPortfolioJSON,
  exportPortfolioMarkdown,
  exportPortfolioCSV,
  getPortfolioStats
};
